spring.application.name=bookshop-api

# ===== H2 Database =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== Postgres Database =====
spring.datasource.url=jdbc:postgresql://localhost:5432/bookshop
spring.datasource.username=postgres
spring.datasource.password=#1a/m@34Bv
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== DataSource =====
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# ===== JPA =====
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===== для data.sql =====
spring.jpa.defer-datasource-initialization=true