spring.application.name=bookshop-api

# ===== Postgres Database =====
spring.datasource.url=jdbc:postgresql://localhost:5432/bookshop
spring.datasource.username=postgres
spring.datasource.password=#1a/m@34Bv
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# ===== JWT =====
# Minimum 32 characters for HS256
jwt.secret=bookshop-super-secret-key-change-me-in-production-32chars
jwt.expiration-ms=86400000
